// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password)
VALUES (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2
)
RETURNING id, created_at, updated_at, email, hashed_password
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users WHERE id IS NOT NULL
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}

const editUserEmail = `-- name: EditUserEmail :exec
UPDATE users 
SET updated_at=NOW(), email=$1
WHERE id = $2
`

type EditUserEmailParams struct {
	Email string
	ID    uuid.UUID
}

func (q *Queries) EditUserEmail(ctx context.Context, arg EditUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, editUserEmail, arg.Email, arg.ID)
	return err
}

const editUserPwd = `-- name: EditUserPwd :exec
UPDATE users 
SET updated_at=NOW(), hashed_password=$1
WHERE id = $2
`

type EditUserPwdParams struct {
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) EditUserPwd(ctx context.Context, arg EditUserPwdParams) error {
	_, err := q.db.ExecContext(ctx, editUserPwd, arg.HashedPassword, arg.ID)
	return err
}

const getUserFromEmail = `-- name: GetUserFromEmail :one
SELECT id, created_at, updated_at, email, hashed_password FROM users WHERE email = $1
`

func (q *Queries) GetUserFromEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const getUserPwdHash = `-- name: GetUserPwdHash :one
SELECT hashed_password FROM users WHERE email = $1
`

func (q *Queries) GetUserPwdHash(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPwdHash, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
